"""add retry_count to crm_sync_log

Revision ID: 22b4f5e1436a
Revises: ff52009bc0c5
Create Date: 2026-03-22 18:05:35.846009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22b4f5e1436a'
down_revision: Union[str, Sequence[str], None] = 'ff52009bc0c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crm_sync_log', sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crm_sync_log', 'retry_count')
    # ### end Alembic commands ###
