"""initial schema

Revision ID: 49ec235a15ed
Revises: 
Create Date: 2026-03-18 17:08:57.199574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49ec235a15ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('source_system', sa.String(length=20), nullable=False),
    sa.Column('lead_origin', sa.String(length=50), nullable=True),
    sa.Column('lead_source', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('current_occupation', sa.String(length=100), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('do_not_email', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('do_not_call', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('total_visits', sa.Float(), nullable=True),
    sa.Column('total_time_spent', sa.Float(), nullable=True),
    sa.Column('page_views_per_visit', sa.Float(), nullable=True),
    sa.Column('last_activity', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.Column('converted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('ix_leads_converted', 'leads', ['converted'], unique=False)
    op.create_index('ix_leads_source_system', 'leads', ['source_system'], unique=False)
    op.create_table('model_registry',
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('artifact_path', sa.String(length=500), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feature_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_index('ix_model_registry_active', 'model_registry', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_table('crm_sync_log',
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('source_system', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('success', 'failed', 'pending')", name='ck_crm_sync_log_status'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_crm_sync_log_lead_id', 'crm_sync_log', ['lead_id'], unique=False)
    op.create_index('ix_crm_sync_log_source_external', 'crm_sync_log', ['source_system', 'external_id'], unique=False)
    op.create_index('ix_crm_sync_log_status', 'crm_sync_log', ['status'], unique=False)
    op.create_table('predictions',
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('bucket', sa.String(length=10), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('feature_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("bucket IN ('A', 'B', 'C', 'D')", name='ck_predictions_bucket'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_predictions_lead_id', 'predictions', ['lead_id'], unique=False)
    op.create_index('ix_predictions_lead_id_scored_at', 'predictions', ['lead_id', sa.literal_column('scored_at DESC')], unique=False)
    op.create_index('ix_predictions_model_version', 'predictions', ['model_version'], unique=False)
    op.create_index('ix_predictions_scored_at', 'predictions', ['scored_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_predictions_scored_at', table_name='predictions')
    op.drop_index('ix_predictions_model_version', table_name='predictions')
    op.drop_index('ix_predictions_lead_id_scored_at', table_name='predictions')
    op.drop_index('ix_predictions_lead_id', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_crm_sync_log_status', table_name='crm_sync_log')
    op.drop_index('ix_crm_sync_log_source_external', table_name='crm_sync_log')
    op.drop_index('ix_crm_sync_log_lead_id', table_name='crm_sync_log')
    op.drop_table('crm_sync_log')
    op.drop_index('ix_model_registry_active', table_name='model_registry', postgresql_where=sa.text('is_active = true'))
    op.drop_table('model_registry')
    op.drop_index('ix_leads_source_system', table_name='leads')
    op.drop_index('ix_leads_converted', table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
