"""add retraining_runs table

Revision ID: e4ef370cc0c3
Revises: 22b4f5e1436a
Create Date: 2026-03-28 12:49:20.467827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4ef370cc0c3'
down_revision: Union[str, Sequence[str], None] = '22b4f5e1436a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retraining_runs',
    sa.Column('run_status', sa.String(length=20), nullable=False),
    sa.Column('candidate_version', sa.String(length=20), nullable=False),
    sa.Column('active_version_before', sa.String(length=20), nullable=True),
    sa.Column('promoted', sa.Boolean(), nullable=False),
    sa.Column('current_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('candidate_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metric_deltas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comparison_reason', sa.Text(), nullable=True),
    sa.Column('drift_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feature_baselines', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('training_data_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('triggered_by', sa.String(length=20), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("run_status IN ('success', 'blocked', 'failed')", name='ck_retraining_runs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_retraining_runs_started_at', 'retraining_runs', ['started_at'], unique=False)
    op.create_index('ix_retraining_runs_status', 'retraining_runs', ['run_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_retraining_runs_status', table_name='retraining_runs')
    op.drop_index('ix_retraining_runs_started_at', table_name='retraining_runs')
    op.drop_table('retraining_runs')
    # ### end Alembic commands ###
